name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Rodar todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: joaoalonsocasella  # Seu usuário GitHub aqui
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Push SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Para o branch output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
